subst.table <- matrix(
  c("Arm|povertystatus|^se\\$.*|Schooling|sex|dummy", "",
    "I\\((.*?)\\)", "\\1",
    "factor\\((.*?)\\)", "\\1",
    "Time.?2", "rd 1 - 2",
    "Time.?3", "rd 2 - 3",
    "Time.?4", "rd 3 - 4",
    "RMvalue.(.*)", "6M \\1",
    "RM(.*)", "6M \\1",
    "[rR]epay", "repayment",
    "dummy", "",
    "LargeSize", "Upfront",
    "NetSaving", "net saving",
    "Other", "other member ",
    "\\.", " $\\\\times$ ",
    "Lag(.*)", "\\1$_{t-1}$",
    "HeadLiteracy", "Head literate",
    "HeadAge", "Head age",
    "^OtherR.*d\\$", "Mean other repayment$",
    "^CumR.*d\\$", "Cumulative repayment$",
    "^CumR.*e\\$", "Cumulative repayment rate$",
    "^CumR.*Q\\$", "Cumulative repayment rate$^{2}",
    "^CumN.*g\\$", "Cumulative net saving$",
    "CumOtherO.*d\\$", "Other cumulative repayments$",
    "CumOtherR.*e\\$", "Other cumulative repayment rate$",
    "CumOtherR.*Q\\$", "Other cumulative repayment rate$^{2}",
    "MeanCumGroupNet.*g\\$", "Per member cumulative group net saving (1000Tk)$",
    "instruments \\((.*?)\\)", "IV: \\1",
    "MeanG.*g\\$", "Per member group net saving$",
    "\\^2", "$^{2}$",
    "Junior", "Secondary",
    "High", "College"), byrow = T, ncol = 2)
